dataset:
  batch_size: 16

model:
  architecture: "shallow_relu"
  save_path_base: "models/model"

train:
  epochs: 3
  lr: 0.001
  seed: 42

log:
  wandb: true
  project: "sweep_test"
  run_name: "debug_run"
