project: sweep_test
name: sweep_experiment_baseline

method: grid
parameters:
  train.lr:
    values: [0.001, 0.01]
  train.epochs:
    values: [5, 10]
  model.architecture:
    values: ["shallow_relu", "deep_tanh"]

metric:
  goal: minimize
  name: val_mae

program: src/main.py
command:
  - ${env}
  - python
  - ${program}
  - --config
  - config/base.yaml
