dataset:
  patch_size: 14
  num_patches: 16
  valid_fraction: 0.2
  batch_size: 8
  canvas_size_w: 56
  canvas_size_h: 56
  grid_rows: 2
  grid_cols: 2
  num_digits: 4
  placement: grid
  num_digits_range: null
  num_images: 100000
  num_images_test: 20000
  cache_dir: "/root/"

model:
  embed_dim: 256
  num_heads: 8
  mlp_dim: 128
  num_layers_encoder: 6
  num_layers_decoder: 6
  num_patches: 16
  add_pos_emb: true
  dropout: 0.2
  dot_product_norm: true

  save_path_base: "/root/models/vision_to_sequence_grid"

train:
  epochs: 2
  lr: 0.0001
  seed: 42

log:
  wandb: true
  project: "vision_to_sequence"
  run_name: "test"
