dataset:
  batch_size: 32

model:
  save_path_base: "/Users/anton/mlx/src/week5/models/model"

train:
  epochs: 10
  lr: 0.001
  seed: 42

log:
  wandb: false
  project: "urban_sounds"
  run_name: "test"
