dataset:
  name: "danavery/urbansound8K"
  batch_size: 32
  sample_rate: 22050
  n_fft: 1024
  hop_length: 512
  num_mels: 64
  max_duration: 4
  num_classes: 10

model:
  save_path_base: "/Users/anton/mlx/src/week5/models/model"

train:
  epochs: 10
  lr: 0.001
  seed: 42

log:
  wandb: false
  project: "urban_sounds"
  run_name: "test"
