project: "ms-marco-ranking"

dataset:
  name: "microsoft/ms_marco"
  version: "v1.1"
  batch_size: 64
  cache_dir: "/Users/anton/experiment_data/datasets/ms_marco"

embeddings:
  # path: "/Users/anton/experiment_data/models/glove.6B/glove.6B.50d.w2v.txt"
  path: "/Users/anton/experiment_data/models/GoogleNews-vectors-negative300/GoogleNews-vectors-negative300.bin"  
  is_binary: true

model:
  type: "avg_w2v_encoder"
  hidden_dims: [200, 100]

train:
  epochs: 3
  lr: 0.001
  seed: 42
  # output: "/Users/anton/mlx/src/week2/models/glove_avg_proj.pt"
  output: "/Users/anton/mlx/src/week2/models/googlenews_avg_proj.pt"

log:
  wandb: true
  project: "ms-marco-ranking"
  run_name: "googlenews_avg_proj"
