dataset:
  patch_size: 14
  num_patches: 4
  valid_fraction: 0.2
  batch_size: 64
  num_classes: 10
  cache_dir: "/Users/anton/experiment_data/datasets"

model:
  embed_dim: 64
  num_heads: 4
  mlp_dim: 128
  num_transformer_layers: 6

  save_path: "/Users/anton/mlx/src/week3_vt_number_classification/models/model"

train:
  epochs: 10
  lr: 0.0003
  seed: 42

log:
  wandb: false
  project: "vt_num_classification"
  run_name: "test"
