models:
  - name: "CLIP (frozen) + MLP (trained) + Custom Transformer (trained)"
    decoder: "custom"
    path: "/Users/anton/mlx/src/week4/final_models/custom.pt"
  - name: "CLIP (frozen) + MLP (trained) + DistilGPT2 (frozen) "
    decoder: "gpt2"
    path: "/Users/anton/mlx/src/week4/final_models/gpt2_tune_only_mlp.pt"
  - name: "CLIP (frozen) + MLP (trained) + DistilGPT2 (fine-tuned)"
    decoder: "gpt2"
    path: "/Users/anton/mlx/src/week4/final_models/gpt2_full_finetuning.pt"
  # - name: "CLIP + MLP 2L + DistilGPT2 (fine-tuned)"
  #   decoder: "gpt2"
  #   path: "/Users/anton/mlx/src/week4/final_models/gpt2_full_finetuning_two_layer_mlp.pt"
  # - name: "CLIP + MLP + Qwen3-0.6B (frozen)"
  #   decoder: "qwen"
  #   path: ""
  - name: "CLIP (frozen) + MLP (trained) + Qwen3-0.6B (fine-tuned)"
    decoder: "qwen"
    path: "/Users/anton/mlx/src/week4/final_models/qwen.pt"
