dataset:
  patch_size: 14
  num_patches: 4
  valid_fraction: 0.2
  batch_size: 64
  canvas_size: (56, 56)
  num_digits: 10
  placement: grid
  num_digits_range: none
  num_images: 10000
  num_images_test: 2000
  cache_dir: "/Users/anton/experiment_data/datasets"

model:
  embed_dim: 64
  num_heads: 4
  mlp_dim: 128
  num_layers_encoder: 6
  num_layers_decoder: 6
  num_patches: 16
  add_pos_emb: true
  dropout: 0.0
  dot_product_norm: true

  save_path_base: "/Users/anton/mlx/src/week3/models/vision_to_sequence"

train:
  epochs: 2
  lr: 0.001
  seed: 42

log:
  wandb: true
  project: "vision_to_sequence"
  run_name: "test"
