dataset:
  patch_size: 14
  num_patches: 36
  valid_fraction: 0.2
  batch_size: 8
  canvas_size_w: 84
  canvas_size_h: 84
  grid_rows: 3
  grid_cols: 3
  num_digits: null
  placement: random
  num_digits_range: [0, 9]
  num_images: 100
  num_images_test: 20
  cache_dir: "/Users/anton/experiment_data/datasets"

model:
  embed_dim: 64
  num_heads: 4
  mlp_dim: 128
  num_layers_encoder: 6
  num_layers_decoder: 6
  num_patches: 36           # FIXME this parameter also exists in dataset section
  add_pos_emb: true
  dropout: 0.0
  dot_product_norm: true

  save_path_base: "/Users/anton/mlx/src/week3/models/vision_to_sequence"

train:
  epochs: 5
  lr: 0.001
  seed: 42

log:
  wandb: true
  project: "vision_to_sequence"
  run_name: "test"
